### ISSUE TITLE
Bugs: New List

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1016]
A list of current UI bugs on my radar. cc @meiqimichelle for visibility

Spillover #984 
I reduced the list and closed out the last issue for clarity/sanity/easier reference

CSS/layout:
* [x] #949 - Site doesn't display properly on mobile
* [x] #810 - Content hitting edge of browser _in review_
* [ ] #998 - **Brian** Replace large diving graphic images with latest (gray, no colors) ~~@gemfarmer is there an issue for this that you know about? @meiqimichelle is #988 what you are talking about?~~ will get images from @ericronne once he is done with charts/graphs
* [x] #838 - @gemfarmer this issue might be elsewhere, too. It is about making the filters on the explore pages sticky, and the filter toggle open over the map. What do you think? @meiqimichelle I'll do it tonight!

Explore page-specific:
* [x] #977 **BRIAN** - All Lands Production
* [x] #993 All Lands Production – break coal down to county
* [x] #992 All Lands Production – Add offshore areas _oil `Pacific alaska` still needs work_
* [x] #1020 All Lands > Coal – Refuse Recovery
* [x] #1026 All Lands Production > Gas and Crude Oil total incorrect
