### ISSUE TITLE
Visual Bugs Epic

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1229]
A list of bugs to squash with issue references (if they exist)

~~strike-through~~ indicates that it has been merged.

~~* [x] select icon~~
~~* [x] search bar text verticality~~
~~* [x] spacing on top of pages for all non-banner pages~~
~~* [x] realign and resize images on about~~
~~* [x] `itital` typo~~
* [x] #1204 
* [x] #1205
* [ ] #938 - right side glossary spacing
* [x] #1216 - change map border stroke color to `#ccc` 
* [x] #1230 - corporate income tax chart

**Comment by ericronne** [comment]
Two new candidates for consideration (global changes) ...
 - [ ] Increase the opacity of the filter blue background
 - [ ] Narrow company search field in desktop view

**Comment by gemfarmer** [comment]
All tasks have been completed except #938, which has its own issue.
