### ISSUE TITLE
New data structure cleanup checklist

### ISSUE THREAD

**Issue by shawnbot** [18F/doi-extractives-data#1369]
There are a bunch of things that we need to do to wrap up our migration from [lots-of-little-node-scripts](https://github.com/18F/doi-extractives-data/tree/dev/data/bin)-and-[flat](https://github.com/18F/doi-extractives-data/tree/dev/data/state)-[files](https://github.com/18F/doi-extractives-data/tree/dev/data/county) to one-little-database-and-a-bunch-of-SQL.

Here are some of the things that we can do _before_ state pages get merged:

- [x] Tidy up our Jekyll data generation process. Right now, there are a series of steps that need to be executed in the right order to get the data from the input files into the `_data` directory where Jekyll can use it. This should be a one-step thing. Maybe the `Makefile` should be moved into the project root or `_data` directory?
- [x] Write some data tests! These should read YAML files from the `_data` directory to ensure that we're getting the right data out of the process, rather than querying the (intermediate) database or flat file inputs.
- [x] Remove files that are unused in the old implementation, like [the deprecated revenue data](https://github.com/18F/doi-extractives-data/blob/dev/data/_input/onrr/county-production.tsv).
- [x] Remove unused [data scripts](https://github.com/18F/doi-extractives-data/tree/dev/data/bin).
- [x] Simplify some of the database imports using `tito --map` and  `--filter` [transforms](https://github.com/shawnbot/tito#map-and-filter-your-data) rather than [Sequelize models](https://github.com/18F/doi-extractives-data/blob/70b6b67930f7695697a2d476499806cec4544b8e/data/db/models/all_production_coal.js). See state disbursements [in createdb.sh](https://github.com/18F/doi-extractives-data/blob/70b6b67930f7695697a2d476499806cec4544b8e/data/createdb.sh#L107-L110) and [the associated transform](https://github.com/18F/doi-extractives-data/blob/70b6b67930f7695697a2d476499806cec4544b8e/data/_input/onrr/disbursements/state.js) for an example.
- [x] Replace the [unroll-columns.js](https://github.com/18F/doi-extractives-data/blob/70b6b67930f7695697a2d476499806cec4544b8e/data/bin/unroll-columns.js) script with `tito` transforms that return multiple output rows per input row. This would need to be implemented in [fof.stream()](https://github.com/shawnbot/fof#fofstreamx-options) and in [tito](https://github.com/shawnbot/tito), but it's a worthwhile addition and can be unit tested in those projects rather than this one.

And then, after the state pages get merged and we no longer need most of the flat files for the front end, we can do the following:

- [x] Remove all of the old flat file targets from the [data/Makefile](https://github.com/18F/doi-extractives-data/blob/dev/data/Makefile).
- [x] Further pare down the [data/bin directory](https://github.com/18F/doi-extractives-data/blob/dev/data/bin/), removing all of the unused scripts.
- [x] Remove a bunch of old [front end JS](https://github.com/18F/doi-extractives-data/tree/70b6b67930f7695697a2d476499806cec4544b8e/js/pages) from the deprecated explore data sections.
- [ ] ~~Remove any unused dependencies from the [package.json](https://github.com/18F/doi-extractives-data/blob/dev/package.json) (in both `dependencies` and `devDependencies`)~~. _moved to_ #1823
- [ ] Consolidate all of the geo and SVG stuff into the `/maps` directory.

Whew, that's actually a lot. @gemfarmer, anything else off the top of your head?

**Comment by gemfarmer** [comment]
maybe update `README` for each dataset's transformation?
- where the data came from originally
- point to yml file where site uses that data
- necessary commands/tools needed to make those transformations
- where to find them in our project

**Comment by shawnbot** [comment]
I like this idea, @gemfarmer. Maybe we should consider a reorganization of the whole `data/_input` directory and put each data source's input file(s), transform(s), and output file(s) in its own directory? This would give us an excuse to go back and make sure that the different forms of data all have the same name, like `data/federal-revenue` instead of `_input/onrr/*-revenues.tsv`. Then the README in each directory could be the source of truth and we could link to those from the [data catalog](https://github.com/18F/doi-extractives-data/wiki/Data-Catalog).

**Comment by gemfarmer** [comment]
@shawnbot Yes, I like that a lot. As someone who frequently visits the `data` directory after leaving it unattended for awhile, I'm always having to check the Makefile to see what is creating what. But a structure like that would add many, many clarity points 💯

**Comment by shawnbot** [comment]
You can see an example of how this—putting each dataset in its own directory with a README and its associated transforms—might work in 062313bfbf25ae85276e91e3c70ccd57d8011092.

**Comment by meiqimichelle** [comment]
@shawnbot Is this still relevant? Should we keep this issue open?

**Comment by meiqimichelle** [comment]
This is more like an epic -- list of reminders. We'll keep pushing it through sprints so we remember these tasks.

**Comment by shawnbot** [comment]
95% done. Moved dependency and SVG cleanup tasks to #1823 and #1824, respectively.
