### ISSUE TITLE
Code: new state pages  design

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1431]
A code to do list for the designs dropped in #1348 

* [x] #1437 –  Adjust grid to 9-3 grid, potentially max width to 960px
* [ ] #1434 – Sparklines OR barcharts component (test first)
* [ ] #1433 –  [Commodity revenues table with tabs](https://github.com/18F/doi-extractives-data/issues/1348#issuecomment-221405579)
* [ ] #1436 – Update chart styles for county-level data
* [ ] #1430 – Add map legends
* [ ] #1432 – Modified sticky nav w/submenu
* [ ] #1435 – Create tile view for Spartlines or barcharts

**Comment by meiqimichelle** [comment]
OBE
