### ISSUE TITLE
State pages: Clarify types of jobs data

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1462]
On the state pages, we need to make sure the jobs data is clear and accurate, and the distinction between self-employment and full-time jobs is clear to users. It's currently a little unclear whether we're combining them or not, so this may take a little teasing out.

Current dev version on `state-pages`:
<img width="773" alt="screenshot 2016-06-22 16 48 16" src="https://cloud.githubusercontent.com/assets/4827522/16287579/27df57c4-3899-11e6-8315-e57168af9c3b.png">

**Comment by coreycaitlin** [comment]
- Currently pulling Wage & Salary
- We have county-level data for Wage & Salary
- We don't have county-level data for Self-Employed

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] @coreycaitlin write intro content about the difference between these datasets
- [ ] @ericronne will start designing
- [ ] @gemfarmer will pull in the Self-Employment dataset

**Comment by ericronne** [comment]
Here's a crack at the design, please lmk your thoughts @coreycaitlin @meiqimichelle @gemfarmer @shawnbot.

I've evolved the side-by-side chart design pioneered in issue #1492, so if this design is deemed Worthy, it should be applied there, too.

Notes:
 - Moved the year selector to the left, to make it easier to find, and to further reinforce that it impacts everything in that section
 - Used "Show table" for the county details button label, since its literally what will be revealed
 - The self-employment chart is a bit of a widow, hanging down there on its own, but i put it there to keep it clearly separated from the wage and salary material
 - In the table, i didn't show a bar chart for percentages. Can see about fitting it in, if need be, but it felt busy to me

## Default
![employment](https://cloud.githubusercontent.com/assets/9259185/16417448/85931e2a-3d0b-11e6-9b0d-9e23b2a56f5a.png)
 
## Table expanded
![employment-table-expanded](https://cloud.githubusercontent.com/assets/9259185/16417711/84288948-3d0c-11e6-8ef6-bb5282d37dad.png)

## [Sketch file](https://drive.google.com/open?id=0BwWYNZcEDfwaaTNyOHh6TU41ZFk)

**Comment by coreycaitlin** [comment]
@ericronne Oooh, I really like the selector to the left of the sentence! It just keeps getting clearer. I like the "show table" label, and agree that YOY percentages for the statewide number is too much.

Once you take a look at the language I drafted up, let me know what you think — it might help make the self-employment chart a bit less orphaned. I can also edit it down a tad, I think.

**Comment by ericronne** [comment]
Sweet, thx @coreycaitlin! I'll take a look at the text and integrate with the layouts...

**Comment by ericronne** [comment]
@coreycaitlin can we do a hangout to discuss this text? @meiqimichelle welcome too, natch
![image](https://cloud.githubusercontent.com/assets/9259185/16454426/4fffac30-3dd6-11e6-8acf-355111460c6d.png)

**Comment by ericronne** [comment]
Until then @coreycaitlin @meiqimichelle, here's some food for thought!

This design ...
 - Puts the wage/sal and self-empl definitions into the glossary
 - Adds the self-employment tally to the summary sentence (which updates to match the selected year)
 - Boldfaces the year in that summary sentence

![image](https://cloud.githubusercontent.com/assets/9259185/16457053/c730b3ae-3ddf-11e6-9ac1-66942ccf359e.png)

**Comment by coreycaitlin** [comment]
@ericronne I'll ping you when I'm free!

**Comment by coreycaitlin** [comment]
We talked about this, and hatched a possible solution: flattening the organization a bit so we don't have to deal with quite so many laters of hierarchy. The sub-nav within `Economic impact` would then be:

- GDP
- Wage and salary jobs
- Self-employment
- Exports

**Comment by ericronne** [comment]
Revised layout, accordingly...

![image](https://cloud.githubusercontent.com/assets/9259185/16507151/4c18d76e-3eed-11e6-8f51-c09c6769c4d9.png)

**Comment by meiqimichelle** [comment]
This is ready for implementation but is blocked by the issue to pull in self-employment data.

**Comment by ericronne** [comment]
And here's the expanded chart in the context of the revised design.

![employment-counties-expanded](https://cloud.githubusercontent.com/assets/9259185/16531548/815ad47c-3f92-11e6-845e-758165106cce.png)


## [Sketch file] (https://drive.google.com/open?id=0BwWYNZcEDfwaOWU3b21RMmYzU00)

**Comment by ericronne** [comment]
## [Sketch file w-one-pixel rule added at base] )https://drive.google.com/open?id=0BwWYNZcEDfwaY2RtQU5ZX0psMXc)

see #1556
