### ISSUE TITLE
State pages: Content for opt-in states

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1467]
We need to identify and write the additional content for opt-in states (as well as states with case studies), so that the additional information flows appropriately and feels like an integral part of the page.

**Comment by coreycaitlin** [comment]
Outline options are here: https://docs.google.com/document/d/1t3WCdivYzSPZhUlRarOgzjA2TYJHTWAiUHAax_wH7A0/edit

@meiqimichelle, let's discuss tomorrow!

**Comment by coreycaitlin** [comment]
After discussing with @meiqimichelle, we're thinking it makes the most sense to consolidate opt-in information into one section, both so that it's easier for users to understand what's special for each state and for future maintainability. (In the outlines doc, this is the "upside-down cake" option.)

Next steps:

- Decide on a name for this section
- Get the Montana info consolidated, edited, and into Markdown
- Decide what data we'll need to pull into the page in an interactive or visual way
- Reorganize the general state page template to reflect this outline

**Comment by coreycaitlin** [comment]
Content that still needs a home on this page:

- [ ] State land ownership details --> governance?
- [ ] Production info --> state intro
- [ ] Revenue
- [ ] Disbursements / distribution
- [ ] Tax expenditures
- [ ] Saving and spending
- [ ] Revenue sustainability
- [ ] Footnotes

**Comment by coreycaitlin** [comment]
Next step: Walk through this page with @meiqimichelle and figure out which sections belong in the state profile vs. a downloadable version.

**Comment by coreycaitlin** [comment]
Here's how the sections of the state addition template map to our state profile pages, roughly:

- Federal land ownership ➡️ state intro (all states)
- State land ownership ➡️ Production / State land
- State agencies and how they interact with extractive industries ➡️ State governance / State agencies section (all opt-in and priority states)
- State laws and regulations ➡️ State governance / State laws and regulations
- Production: how much is produced in Montana ➡️ Production / Entire state (all states)
- Production on state land ➡️ Production / State land
- State and local revenue streams ➡️ Revenue / State and local revenue
- Tax expenditures ➡️ State governance / Tax expenditures
- Distribution of state and local revenue ➡️ Disbursements / State and local revenue
- Saving and spending ➡️ Disbursements / State disbursements / Coal Trust Fund
- Impact ➡️ Economic impact
- Revenue sustainability ➡️ Revenue / State and local revenue
- Costs ➡️ State governance / Fiscal costs

**Comment by coreycaitlin** [comment]
Still to-do:

- [ ] Get downloadable version of the revenue streams table
- [ ] Add download link to get PDF of revenue streams table
