### ISSUE TITLE
Content: Write explanation of geothermal rates

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1474]
@meiqimichelle please send source content!

**Comment by meiqimichelle** [comment]
This is some relevant info, but we have to sort out the exact summary stuff we want out of it.
Here is what we have collected so far though:

[Geothermal FAQ.pdf](https://github.com/18F/doi-extractives-data/files/303643/Geothermal.FAQ.pdf)

http://www.blm.gov/wo/st/en/prog/energy/geothermal.html

`I think the one missing thing is royalty rate, which hopefully bob will tell me that`

`so royalty rates aren't 12.5% if you put a placeholder together I'll send it to the ONRR expert and he can fill in the blanks and fact check it.`

**Comment by coreycaitlin** [comment]
Here's what I came up with as a first draft: 

![screen shot 2016-06-20 at 5 23 21 pm](https://cloud.githubusercontent.com/assets/1450354/16214302/ba385b0a-370b-11e6-9a9a-c7f54d5c4ea5.png)

Remaining questions:

- [ ] What are the royalty rates for competitive and noncompetitive leases?
- [ ] Should nomination fees be included here, or are those out-of-scope for this table?
- [ ] Are the initial lease payments called "bonuses" here (as they are for most other resources)? If not, what are they called?
- [ ] Do we need to include pre-2007 and/or pre-2005 rates and fee structures?

Leaving myself tagged as a reminder to check with @mentastc or @usEITI about this language.

**Comment by coreycaitlin** [comment]
Next action: Write up this draft in an email so @mentastc can forward to experts at ONRR.

**Comment by coreycaitlin** [comment]
**Revised language to verify with ONRR:**

The fees and rates for geothermal-extraction revenue seem to depend on whether the land is leased _competitively_ or _noncompetitively_.

For competitive leasing:

* Nomination fees: $110 per nomination + $0.11 per acre
* Lease (is this called a "bonus"?): The amount offered by the highest bidder + $155 processing fee
* Rents: $2 per acre for the first year, $3 annual rent per acre for years 2-10, $5 annual rent per acre thereafter
* Royalties:
    * If [you're selling electricity]: 1.75% of gross proceeds from sale of electricity for the first 10 years of production, then 3.5% 
    * If [you're selling the geothermal resources but someone else is making them into electricity]: 10% of gross proceeds from arm's-length sale of the resources

For noncompetitive leasing:

* Lease: $400 payment
* Rents: $1 annual rent per acre for 10 years, $5 annual rent per acre thereafter
* Royalties:
    * If [you're selling electricity]: 1.75% of gross proceeds from sale of electricity for the first 10 years of production, then 3.5% 
    * If [you're selling the geothermal resources but someone else is making them into electricity]: 10% of gross proceeds from arm's-length sale of the resources

It looks like there are separate terms for leases issued before August 2005 — I'm hoping we can include a simple asterisk with a note to the effect of "Royalty rates may be different for leases issued before August 8, 2005."

**Comment by coreycaitlin** [comment]
Progress in #1459.

**Comment by coreycaitlin** [comment]
I think this is about as correct/clear as we can be within this table — I'm going to punt the details and link-finding to issue #1560 so we have a bit more space to cover all the bases.
