### ISSUE TITLE
Revenues megachart needs to fully match the mock

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1559]
This is a continuation of #1459. We're closer to matching the designs, but not 100% there. See:

## [Invision prototype](https://invis.io/827QI8DGR#/168829791_Revenue-By-Phases)

**Comment by ericronne** [comment]
FYI, notes from a test of the **[three-tabbed invision prototype] (https://invis.io/827QI8DGR)** yesterday....

**Megachart prototype** (including the totals tab)
 - When told that the totals tab was going away, he said, “That’s too bad.” Felt it was a lot easier to understand than phases, and thought it should be the default view, that it would be “right to start with the high level.”
 - “For a newbie like me, it would be helpful to have a sentence to describe/explain” [what’s going on]
 - Liked the icons

I mostly post this because of the totals comment. Previous testers have commented positively on it. A few notes from those user tests...

 **18F front end designer**
 - Felt the totals tab view was much easier to digest than the phase breakdown, suggested that it be the default

**18F product manager**
 - Total summary at the bottom helped him understand; thought it might be more helpful at the top
 - Immediately understood the totals-tab view, and felt it was more a more evident total of everything
 - Suggested that the totals tab be first in the row, so that the information starts big and then gets granular. But immediately realized that you might miss the (current) first tab if it wasn’t visible by default.

**18F visual designer**
 - Wondered if this should be the default view, and could you have a “show details” feature to view the breakdown we have on the phases tab

Don't mean to gum up the works, just food for chat! :)

**[Test notes] (https://docs.google.com/a/gsa.gov/document/d/1IO1pYisQ6G7rk2iKQif-k8Cy52-OvWWPXGPkEiFODn4/edit?usp=sharing)**

**Comment by meiqimichelle** [comment]
Much food! Great! I wonder how close we are to another testing cycle with our target audience(s)? By that point, I'd hope we'd have the state pages pretty clean. What do you think about next sprint @coreycaitlin ?

**Comment by ericronne** [comment]
Misc nits ...
 - [ ] Commodity subheads (eg "COAL") sb 0.8125 rem (13px) (appear to be 0.875 rem)
 - [ ] Height of bars sb 0.625 (10px) (currently 1 rem)
 - [ ] Bar backgrounds sb $gray-pale (currently $gray-light)
 - [ ] The data portion of bars sb #587f4c (which is what i have for $green) (currently #657c60)
 - [ ] The darker green bar portion (eg gas) sb #2f4d26 (which is what i have for $green-darkest) (currently #2E4E24)

 - [ ] And more that's easier put into an image...
![image](https://cloud.githubusercontent.com/assets/9259185/18531052/ef703690-7a99-11e6-953f-353ea3191983.png)

i **think** that's it!

**Comment by ericronne** [comment]
💥
