### ISSUE TITLE
Layout spillover

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1597]
#### Remaining work from #1592, #1518 
---
- [x] Federal production data isn't working on some states (see Arizona and Washington) (perhaps it is the states that have the random 100 years of data for a few commodities) --mhz
- [x] map legend years need to update on year switch
- [x] Map legend filtering needs to update without white space
- [ ] Color swatches on map should based on absolute (rather than relative) scale
- [ ] ~~add year switcher functionality to the mega chart (probably means making the megachart a component)~~ We don't need to look at every year here. --mhz
- [ ] ~~bar chart sentences need to handle `$0` values~~ discussed [here](https://github.com/18F/doi-extractives-data/issues/1556#issuecomment-230521577)
- [ ] ~~bar charts need to handle 0 values~~ new issue for this [here](https://github.com/18F/doi-extractives-data/issues/1675)
- [x] when sections don't have any data for any years, hide selector, bar chart and map
- [ ] fix uneven heights on `.chart-title` element (easiest solution here is to make all headers short enough to fit on one line)
- [x] get rid of "Details" toggles that are no longer needed. Remove commented out code.
- [x] wide maps should have horizontal legend [see this comment](https://github.com/18F/doi-extractives-data/issues/1492#issuecomment-228353485)
#### Things that need to update when a year is switched (and currently aren't updating)
---
- [x] legend description
- [x] Section description. Currently if the page is rendered on a year, that text is set to that year, even if another year might have different associated text
- [x] county-level bar charts

**Comment by ericronne** [comment]
I'm marking up some typographic adjustments, but here are a few other tweaks for starters (mostly re bar styling). Thx @gemfarmer! ...

- [ ] Create a new section header, "Production in the entire state of Utah" (see image below).
- [ ] Extra space should go above single-line heads, not below it.
- [ ] Numbers and text in surrounding sentences seem large.
- [ ] If @coreycaitlin agrees, delete the periods after data sentences
- [ ] Can we slightly reduce the vertical space between the tops of the bars and the data sentence above them?
- [ ] ENHANCEMEHT: testing surfaced the need for a Y-axis label, which could look like the inset design below. 
- [ ] Charts are too close horizontally, see image here (padding on right)

![image](https://cloud.githubusercontent.com/assets/9259185/16876735/b15713ce-4a6a-11e6-8cc6-0758e8ebf158.png)

**Comment by ericronne** [comment]
@gemfarmer 
Here's a reference image for some type fixes, tyvm!...

![image](https://cloud.githubusercontent.com/assets/9259185/16877640/c9246a16-4a6e-11e6-9f27-83638ff1c04a.png)

**Comment by gemfarmer** [comment]
- tile header alignment: if there is a discrepancy between chart-title heights, make the one-row title hug the line rule with space above it.
