### ISSUE TITLE
State pages: Land ownership maps/content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1607]
We've heard feedback that it would be good to have some additional styling and content re: land ownership:

- [ ] ~~Numbers or percentages to include in sentences about state land and/or tribal land (do we have this data?)~~ We do *not* have this data without a lot of manual work
- [ ] Add link to data source for land ownership info
- [ ] Revise the content to illuminate state and private land, even if we don't have data on it?

**Comment by coreycaitlin** [comment]
See also #1391

**Comment by coreycaitlin** [comment]
Closing this out in favor of #1692 and #1391.
