### ISSUE TITLE
Epic: Data bugs

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1727]
- [x] ~~#1693 Offshore data – WIP #1690~~
- [x] ~~#1704 Withheld data~~
- [x] ~~#1673 State jobs data not accurate –– Brian~~
- [x] ~~#1671 Inconsistency with revenue FIPS # –– Shawn~~
- [x] ~~#1655 include counties that have a FIPS but no name –– Shawn~~
- [x] ~~#1675 Need to differentiate between 0 and 'no data' –– Brian~~
- [x] ~~#1692 Find and integrate state land ownership data –– Shawn~~
- [x] ~~#1728 Refactor disbursements data tests –– Brian~~
- [x] Replace download links for federal production data -- Brian
  - [x] remove offshore.tsv
  - [x] add new excel document and link to it. 
- [ ]  #1820 Fix generation of federal production data -- Brian

cc @shawnbot

**Comment by gemfarmer** [comment]
Notes from disbursements pairing:

- One thing that we discovered is that our tests are brittle. If the fields aren't simply updated, but the structure changes, our entire test suite falls down
- One proposal to address this is to test specific fields  in the raw input data to pin-point potentially hazardous field names and/or values in the data. Examples of this are:
  - 'FY' vs 'Fiscal Year' as a field name
  - checking blanks
  - 'State' vs 'States' for Fund in the federal disbursements data
- Generating pivot tables from sqlite to test the data nesting process. Specifically that nestly doesn't warn if you are outputting a value for more than one row.
  - @shawnbot _might_ update nestly to (optionally) handle this
- Potentially add a README within each directory that generally states what the tests are testing.

**Comment by gemfarmer** [comment]
Note: remove percent values on the output yml files for all datasets _but_ jobs.

**Comment by shawnbot** [comment]
WE ARE SO CLOSE.

**Comment by meiqimichelle** [comment]
Overtaken by #1820 where the remainder of these live. Closing! We ARE so close!
