### ISSUE TITLE
Visual bugs: sticky side nav

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1756]
- [x] Only the items in the expanded nav should be indented. All of the text that shows by default should be left aligned (see image below)
 - [ ] The map should match the comp below as closely as possible (Alaska higher than Hawaii, show offshore regions, etc.). Can it be an svg?

![image](https://cloud.githubusercontent.com/assets/9259185/17749523/a63f0540-6483-11e6-9d16-2f4fb670f565.png)

 - [ ] Whoops this seems to be new: the nav shouldn't be spaced out vertically like this (on dev) ...

![image](https://cloud.githubusercontent.com/assets/9259185/17749042/bff39eda-6481-11e6-9315-a3c7d1ea2c66.png)

The [layout-refinements] (https://federalist.18f.gov/preview/18F/doi-extractives-data/layout-refinements/states/UT/) branch behaves better. Just a few bugs there (in addition to the first two noted here in this issue)....

 - [x] The nav shouldn't jump around / resize when submenus expand

![image](https://cloud.githubusercontent.com/assets/9259185/17749851/1cc329ca-6485-11e6-8bb6-00f81d8d7f8f.png)

![image](https://cloud.githubusercontent.com/assets/9259185/17749863/2df24802-6485-11e6-9875-3d3859186784.png)

**Comment by meiqimichelle** [comment]
This is done except for the placement of Alaska. We may explore that in a separate issue. Closing for now.
