### ISSUE TITLE
Megachart bugs

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2082]
- [ ] **There's a stray narrow strip of #d3dfe6 gray to the right of the Oil / Gas / NGL bars** (also appears when there's no data to show)

eg Illinois …
![image](https://cloud.githubusercontent.com/assets/9259185/19309825/cccdc99a-904c-11e6-8aa4-fd401f684c78.png)

eg Idaho …
![image](https://cloud.githubusercontent.com/assets/9259185/19309847/ee4ad964-904c-11e6-92b7-45bff036f9b3.png)
- [x] **Oil / Gas / NGL should each break onto their own lines**
  Eg Alaska (i recall seeing an issue for this, but i can't locate it) …
  ![image](https://cloud.githubusercontent.com/assets/9259185/19312107/a6975bf6-9056-11e6-9956-61757633ba78.png)
- [x] **NGL wasn't included in the original design. Let's color it $gray-darker** (#5c7380, currently #1a2b15)

**Comment by gemfarmer** [comment]
This is done!
