### ISSUE TITLE
Remaining *major issues

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2109]
remaining to-do list:
### Sticky nav:
- [x] sticky navigation bugs
- [x] return to top should go to top
- [x] mobile sticky nav should say “Nationwide data” instead of Explore Data
### General mobile stuff:
- [x] megachart: 
  - [x] fix tabs overlapping/stacking issue
  - [x] fix header sizing
- [ ] Potentially collapsible megachart and disbursements chart --> #1670
- [ ] disable clicking on the US explore map on mobile --> #2165
- [x] disbursements table look/feel
- [ ] get rid of unused images --> #2163
- [x] restore correct error pages
- [ ] minify css --> #2164

cc @ericronne

**Comment by meiqimichelle** [comment]
Moved remaining points to separate issues. Closing! 🎉
