### ISSUE TITLE
Filtering checklist

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2288]
Potential avenues:

- [ ] continue filtering by commodity (megachart)
- [ ] filtering by topic (all production, revenue, disbursements, etc.)
- [ ] "enter share mode", provide sharing options for specific content, links, etc., sharing one thing

**Comment by coreycaitlin** [comment]
This is connected to #2279

**Comment by coreycaitlin** [comment]
Closing this out — will tackle anew if filtering and sharing come up as user needs in the future.
