### ISSUE TITLE
Build fractal style guide

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2360]
I'd like a style guide for the USEITI website, so we (ONRR) can maintain and extend the design vocabulary as the site evolves.

**Comment by gemfarmer** [comment]
We might consider using [Fractal](http://fractal.build/) as the backbone of a new style guide. There are a few 18F projects, including USWDS that have used it successfully without too much overhead.

**Comment by winzenburg** [comment]
Looking for a font that works better across browser

**Comment by ericronne** [comment]
#875 is the root issue. We may stick with Lato, if we don't find a killer alt soon.

**Comment by ericronne** [comment]
Before he left the premises, Brian recommended that we scrap the current style guide and start over from scratch. The current one is very out of date, and likely not worth keeping.

**Comment by ericronne** [comment]
@msecret

**Comment by msecret** [comment]
The best option these days is to use something like [fractal](https://github.com/frctl/fractal).

**Comment by ericronne** [comment]
Check out (and off) these fun steps!
(more to come) …
- [ ] Stub out basic Fractal shell #2443
- [ ] Conduct a style inventory #2444
- [ ] Simplify type styles @2445
- [ ] Adjust grids and spacing #2446

**Comment by ericronne** [comment]
For better tracking, should we create two new documentation issues to add to the checklist: technical (@msecret) and "content" (@coreycaitlin)? 

Then we could close out #2482 (after narrowing it to "mvp documentation" eg) and check off that box.

**Comment by coreycaitlin** [comment]
Let's keep this open until we've cleared up a few remaining issues with the build process.

**Comment by coreycaitlin** [comment]
We also need to test this locally on ONRR machines, using Docker.

**Comment by coreycaitlin** [comment]
Next step: @jeremiak and @mentastc to test during pairing today, @brentryanjohnson to test on his machine.

**Comment by coreycaitlin** [comment]
We've opened #2620 to reflect the work on running the style guide locally. Closing this issue out now, since all work is reflected elsewhere.
