### ISSUE TITLE
Build out a rough product roadmap

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2666]
Now that we have our [product vision](https://github.com/18F/doi-extractives-data/wiki/Product-framing) defined, let's work collaboratively with the core team to built out a first pass of our product roadmap.

This will be done when:
- [x] we've scheduled time for the core team to work on this together (~1.5 hours).
- [x] @jennmalcolm & @brentryanjohnson have made a plan for how they'll facilitate the session and have prepped any needed materials.
- [x] we come out of the session with a rough roadmap that visualizes what chunks of work we'll be prioritizing in the short and medium term.

**Comment by alexpandel** [comment]
I'd say this issue is done, in terms of establishing the higher-level priorities in the short and medium term! Maybe one of you can make a follow-up issue for next sprint that captures the next steps in terms of running a session with the wider team to break those bigger focus areas down into more discrete chunks of work?

**Comment by jennmalcolm** [comment]
I agree, opened #2700 for next step.
