### ISSUE TITLE
Work with core team to build out detail in Roadmap

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2700]
As a result of #2666, we identified our priority areas of focus for now, soon, and later and developed a framework for the product roadmap. Now, we will need to involve the core team to build out the detail in our roadmap.

- [x] Identify activities for next 3 months and tasks for next 6 weeks related to now goal (disbursements)
- [x] Identify activities for next 3 months related to soon goal (outreach)
- [x] Discuss with the core team if there are any activities for the later goal that need to be on our radar in the next 3 months

**Comment by brentryanjohnson** [comment]
Closing this one and implementing roadmap.
