### ISSUE TITLE
Production launch QA checklist

### ISSUE THREAD

**Issue by cscairns** [18F/doi-extractives-data#274]
# Production Launch QA

## Testing
- [ ] Browser test: IE 9-11, Chrome, Firefox, Safari (current versions)
- [ ] Device testing: iPhone (3.5", 4", 4.7"), Android (multiple), iPad.
- [ ] Test with JS turned off
- [ ] Test with CSS turned off
- [ ] Stress test using Blitz.io
- [ ] Server monitoring configured using New Relic
- [x] HTTPS certificate and configuration
- [ ] PC / old display check

## Accessibility
- [ ] WAI-ARIA roles
- [ ] Keyboard navigation
- [ ] Proper form markup
- [ ] Color contrast check
- [ ] Image alt tags
- [ ] Go through 508 checklist
- [ ] Validate using [this tool](http://wave.webaim.org/)

## Content
- [ ] Spell-check and grammar check
- [ ] Retina quality assets (note: retina.js makes it super easy)
- [x] SEO tags
- [ ] Check all links
- ~~"Site of the USA" banner?~~ _will add after out of beta_
- [x] Beta tag / message
- [ ] Privacy policy
- [ ] Accessibility disclaimer
- [ ] Sitemap
- [x] Warning for old browsers
- [ ] Redirects
- [ ] Warning of javascript is turned off
- [x] 404 error page
- [x] Favicon
- [x] Proper email and phone number to contact

## Functionality 
- [x] Schema.org semantics?
- [ ] Confirm Google Analytics working
- [ ] Confirm Google Webmaster working

## Optimization and Validation
- [ ] Cleanup CSS
- [ ] Delete unused files
- [ ] Consolidate CSS and JS requests
- [ ] Lint JS
- [ ] Lint CSS
- [ ] Validate HTML
- [ ] Optimize images

## Social Media
- [x] Facebook metatags
- [x] Twitter metatags
- [x] Facebook and Twitter meta images

**Comment by meiqimichelle** [comment]
OBE
