### ISSUE TITLE
Revenues process illustrated stories

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#561]
There are six different pages in the 'how do resources result in revenues' section, each with its own illustration and details. I've split this issue into sub-issues so we can track the text and illustrations more easily.

- [x] Coal #576 _DONE with #596_
- [x] Oil and Gas: Onshore #577 _DONE with #594_
- [x] Oil and Gas: Offshore _DONE_
- [x] Renewables: Onshore #579 _DONE with #592_
- [x] Renewables: Offshore #578 _DONE with #593_
- [x] Non-energy minerals #580 _DONE with #599_

**Comment by meiqimichelle** [comment]
DONE! :confetti_ball:
