### ISSUE TITLE
Production launch checklist

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#989]
# Production Launch QA

This list is copied from one we used on the last beta launch a year ago. It may need to be modified.

## Testing
- [ ] Browser test: IE 9-11, Chrome, Firefox, Safari (current versions)
- [ ] Device testing: iPhone (3.5", 4", 4.7"), Android (multiple), iPad.
- [ ] Test with JS turned off
- [ ] Test with CSS turned off
- [ ] Stress test using Blitz.io
- [x] HTTPS certificate and configuration
- [ ] PC / old display check

## Accessibility
- [ ] WAI-ARIA roles
- [ ] Keyboard navigation
- [ ] Proper form markup
- [ ] Color contrast check
- [ ] Image alt tags
- [ ] Go through 508 checklist
- [ ] Validate using [this tool](http://wave.webaim.org/)

## Content
- [x] Spell-check and grammar check
- [ ] Retina quality assets (note: retina.js makes it super easy)
- [x] SEO tags
- [x] Check all links
- [x] "Site of the USA" banner
- [x] Beta tag / message
- [ ] Privacy policy
- [x] Sitemap
- [ ] Redirects
- [ ] 404 error page
- [x] Favicon
- [x] Proper email and phone number to contact

## Functionality 
- [ ] Schema.org semantics?
- [x] Confirm Google Analytics working
- [x] Confirm Google Webmaster working

## Optimization and Validation
- [ ] Cleanup CSS
- [ ] Delete unused files
- [ ] Consolidate CSS and JS requests
- [ ] Lint JS
- [ ] Lint CSS
- [ ] Validate HTML
- [ ] Optimize images

## Social Media
- [x] Facebook metatags
- [x] Twitter metatags
- [x] Facebook and Twitter meta images

**Comment by meiqimichelle** [comment]
Overtaken by events.
